// Interface automatically generated by schemas-to-ts

import { Hero } from '../../../../components/sections/interfaces/Hero';
import { Overview } from '../../../../components/sections/interfaces/Overview';
import { Insight } from '../../../insight/content-types/insight/insight';
import { Hero_Plain } from '../../../../components/sections/interfaces/Hero';
import { Overview_Plain } from '../../../../components/sections/interfaces/Overview';
import { Insight_Plain } from '../../../insight/content-types/insight/insight';
import { Hero_NoRelations } from '../../../../components/sections/interfaces/Hero';
import { Overview_NoRelations } from '../../../../components/sections/interfaces/Overview';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface InsightsPage {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    _softDeletedAt?: Date;
    _softDeletedById?: number;
    _softDeletedByType?: string;
    Hero?: Hero;
    Overview: Overview;
    insights: { data: Insight[] };
  };
}
export interface InsightsPage_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  _softDeletedAt?: Date;
  _softDeletedById?: number;
  _softDeletedByType?: string;
  Hero?: Hero_Plain;
  Overview: Overview_Plain;
  insights: Insight_Plain[];
}

export interface InsightsPage_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  _softDeletedAt?: Date;
  _softDeletedById?: number;
  _softDeletedByType?: string;
  Hero?: Hero_NoRelations;
  Overview: Overview_NoRelations;
  insights: number[];
}

export interface InsightsPage_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  _softDeletedAt?: Date;
  _softDeletedById?: number;
  _softDeletedByType?: string;
  Hero?: Hero_Plain;
  Overview: Overview_Plain;
  insights: AdminPanelRelationPropertyModification<Insight_Plain>;
}
