// Interface automatically generated by schemas-to-ts

import { TitleAndDescription } from '../../../../components/sections/interfaces/TitleAndDescription';
import { TitleAndDescription_Plain } from '../../../../components/sections/interfaces/TitleAndDescription';
import { TitleAndDescription_NoRelations } from '../../../../components/sections/interfaces/TitleAndDescription';

export interface PrivacyNoticePage {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    Description?: TitleAndDescription;
  };
}
export interface PrivacyNoticePage_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  Description?: TitleAndDescription_Plain;
}

export interface PrivacyNoticePage_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  Description?: TitleAndDescription_NoRelations;
}

export interface PrivacyNoticePage_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  Description?: TitleAndDescription_Plain;
}
