// Interface automatically generated by schemas-to-ts

import { LabelAndText } from '../../../../components/elements/interfaces/LabelAndText';
import { LabelAndText_Plain } from '../../../../components/elements/interfaces/LabelAndText';
import { LabelAndText_NoRelations } from '../../../../components/elements/interfaces/LabelAndText';

export interface Location {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    _softDeletedAt?: Date;
    _softDeletedById?: number;
    _softDeletedByType?: string;
    street: string;
    building?: string;
    postOfficeBox?: string;
    communication: LabelAndText[];
    city: string;
    slug?: string;
  };
}
export interface Location_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  _softDeletedAt?: Date;
  _softDeletedById?: number;
  _softDeletedByType?: string;
  street: string;
  building?: string;
  postOfficeBox?: string;
  communication: LabelAndText_Plain[];
  city: string;
  slug?: string;
}

export interface Location_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  _softDeletedAt?: Date;
  _softDeletedById?: number;
  _softDeletedByType?: string;
  street: string;
  building?: string;
  postOfficeBox?: string;
  communication: LabelAndText_NoRelations[];
  city: string;
  slug?: string;
}

export interface Location_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  _softDeletedAt?: Date;
  _softDeletedById?: number;
  _softDeletedByType?: string;
  street: string;
  building?: string;
  postOfficeBox?: string;
  communication: LabelAndText_Plain[];
  city: string;
  slug?: string;
}
