// Interface automatically generated by schemas-to-ts

import { TitleAndDescription } from '../../../../components/sections/interfaces/TitleAndDescription';
import { Hero } from '../../../../components/sections/interfaces/Hero';
import { TitleAndDescription_Plain } from '../../../../components/sections/interfaces/TitleAndDescription';
import { Hero_Plain } from '../../../../components/sections/interfaces/Hero';
import { TitleAndDescription_NoRelations } from '../../../../components/sections/interfaces/TitleAndDescription';
import { Hero_NoRelations } from '../../../../components/sections/interfaces/Hero';

export interface CareersPage {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    _softDeletedAt?: Date;
    _softDeletedById?: number;
    _softDeletedByType?: string;
    Overview?: TitleAndDescription;
    Roles?: TitleAndDescription;
    BuildConnectGrow?: TitleAndDescription;
    ConnectingAspirations?: TitleAndDescription;
    Quote?: string;
    GrowingLeaders?: TitleAndDescription;
    FindYourIdealJob?: TitleAndDescription;
    Hero?: Hero;
  };
}
export interface CareersPage_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  _softDeletedAt?: Date;
  _softDeletedById?: number;
  _softDeletedByType?: string;
  Overview?: TitleAndDescription_Plain;
  Roles?: TitleAndDescription_Plain;
  BuildConnectGrow?: TitleAndDescription_Plain;
  ConnectingAspirations?: TitleAndDescription_Plain;
  Quote?: string;
  GrowingLeaders?: TitleAndDescription_Plain;
  FindYourIdealJob?: TitleAndDescription_Plain;
  Hero?: Hero_Plain;
}

export interface CareersPage_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  _softDeletedAt?: Date;
  _softDeletedById?: number;
  _softDeletedByType?: string;
  Overview?: TitleAndDescription_NoRelations;
  Roles?: TitleAndDescription_NoRelations;
  BuildConnectGrow?: TitleAndDescription_NoRelations;
  ConnectingAspirations?: TitleAndDescription_NoRelations;
  Quote?: string;
  GrowingLeaders?: TitleAndDescription_NoRelations;
  FindYourIdealJob?: TitleAndDescription_NoRelations;
  Hero?: Hero_NoRelations;
}

export interface CareersPage_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  _softDeletedAt?: Date;
  _softDeletedById?: number;
  _softDeletedByType?: string;
  Overview?: TitleAndDescription_Plain;
  Roles?: TitleAndDescription_Plain;
  BuildConnectGrow?: TitleAndDescription_Plain;
  ConnectingAspirations?: TitleAndDescription_Plain;
  Quote?: string;
  GrowingLeaders?: TitleAndDescription_Plain;
  FindYourIdealJob?: TitleAndDescription_Plain;
  Hero?: Hero_Plain;
}
