// Interface automatically generated by schemas-to-ts

import { Media } from '../../../common/schemas-to-ts/Media';
import { Media_Plain } from '../../../common/schemas-to-ts/Media';

export enum SocialNetwork {
  Facebook = 'Facebook',
  Twitter = 'Twitter',
  Email = 'Email',
  LinkedIn = 'LinkedIn',
  Instagram = 'Instagram',}

export interface MetaSocial {
  socialNetwork: SocialNetwork;
  title: string;
  description: string;
  image?: { data: Media };
  Url: string;
}
export interface MetaSocial_Plain {
  socialNetwork: SocialNetwork;
  title: string;
  description: string;
  image?: Media_Plain;
  Url: string;
}

export interface MetaSocial_NoRelations {
  socialNetwork: SocialNetwork;
  title: string;
  description: string;
  image?: number;
  Url: string;
}

