// Interface automatically generated by schemas-to-ts

import { LabelAndText } from '../../../../components/elements/interfaces/LabelAndText';
import { Media } from '../../../../common/schemas-to-ts/Media';
import { Overview } from '../../../../components/sections/interfaces/Overview';
import { Expertise } from '../../../expertise/content-types/expertise/expertise';
import { LabelAndText_Plain } from '../../../../components/elements/interfaces/LabelAndText';
import { Media_Plain } from '../../../../common/schemas-to-ts/Media';
import { Overview_Plain } from '../../../../components/sections/interfaces/Overview';
import { Expertise_Plain } from '../../../expertise/content-types/expertise/expertise';
import { LabelAndText_NoRelations } from '../../../../components/elements/interfaces/LabelAndText';
import { Overview_NoRelations } from '../../../../components/sections/interfaces/Overview';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Project {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    _softDeletedAt?: Date;
    _softDeletedById?: number;
    _softDeletedByType?: string;
    Name: string;
    ProjectDetails: LabelAndText[];
    Background: string;
    Assignment: string;
    Image: { data: Media };
    Approach?: Overview;
    Abbreviation: string;
    ProjectType: string;
    Description: string;
    slug: string;
    expertise?: { data: Expertise };
    Impact?: string;
    Scope?: string;
    Goal?: string;
  };
}
export interface Project_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  _softDeletedAt?: Date;
  _softDeletedById?: number;
  _softDeletedByType?: string;
  Name: string;
  ProjectDetails: LabelAndText_Plain[];
  Background: string;
  Assignment: string;
  Image: Media_Plain;
  Approach?: Overview_Plain;
  Abbreviation: string;
  ProjectType: string;
  Description: string;
  slug: string;
  expertise?: Expertise_Plain;
  Impact?: string;
  Scope?: string;
  Goal?: string;
}

export interface Project_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  _softDeletedAt?: Date;
  _softDeletedById?: number;
  _softDeletedByType?: string;
  Name: string;
  ProjectDetails: LabelAndText_NoRelations[];
  Background: string;
  Assignment: string;
  Image: number;
  Approach?: Overview_NoRelations;
  Abbreviation: string;
  ProjectType: string;
  Description: string;
  slug: string;
  expertise?: number;
  Impact?: string;
  Scope?: string;
  Goal?: string;
}

export interface Project_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  _softDeletedAt?: Date;
  _softDeletedById?: number;
  _softDeletedByType?: string;
  Name: string;
  ProjectDetails: LabelAndText_Plain[];
  Background: string;
  Assignment: string;
  Image: AdminPanelRelationPropertyModification<Media_Plain>;
  Approach?: Overview_Plain;
  Abbreviation: string;
  ProjectType: string;
  Description: string;
  slug: string;
  expertise?: AdminPanelRelationPropertyModification<Expertise_Plain>;
  Impact?: string;
  Scope?: string;
  Goal?: string;
}
