// Interface automatically generated by schemas-to-ts

import { Hero } from '../../../../components/sections/interfaces/Hero';
import { Overview } from '../../../../components/sections/interfaces/Overview';
import { Banner } from '../../../../components/sections/interfaces/Banner';
import { Hero_Plain } from '../../../../components/sections/interfaces/Hero';
import { Overview_Plain } from '../../../../components/sections/interfaces/Overview';
import { Banner_Plain } from '../../../../components/sections/interfaces/Banner';
import { Hero_NoRelations } from '../../../../components/sections/interfaces/Hero';
import { Overview_NoRelations } from '../../../../components/sections/interfaces/Overview';
import { Banner_NoRelations } from '../../../../components/sections/interfaces/Banner';

export interface AboutUsSustainability {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    Hero: Hero;
    Overview: Overview;
    MediaBanner?: Banner;
    Body: string;
  };
}
export interface AboutUsSustainability_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  Hero: Hero_Plain;
  Overview: Overview_Plain;
  MediaBanner?: Banner_Plain;
  Body: string;
}

export interface AboutUsSustainability_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  Hero: Hero_NoRelations;
  Overview: Overview_NoRelations;
  MediaBanner?: Banner_NoRelations;
  Body: string;
}

export interface AboutUsSustainability_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  Hero: Hero_Plain;
  Overview: Overview_Plain;
  MediaBanner?: Banner_Plain;
  Body: string;
}
