// Interface automatically generated by schemas-to-ts

export interface ServicesLandingPage {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    Description: string;
  };
}
export interface ServicesLandingPage_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  Description: string;
}

export interface ServicesLandingPage_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  Description: string;
}

export interface ServicesLandingPage_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  Description: string;
}
