// Interface automatically generated by schemas-to-ts

import { TitleAndDescription } from '../../../../components/sections/interfaces/TitleAndDescription';
import { Overview } from '../../../../components/sections/interfaces/Overview';
import { TitleAndDescription_Plain } from '../../../../components/sections/interfaces/TitleAndDescription';
import { Overview_Plain } from '../../../../components/sections/interfaces/Overview';
import { TitleAndDescription_NoRelations } from '../../../../components/sections/interfaces/TitleAndDescription';
import { Overview_NoRelations } from '../../../../components/sections/interfaces/Overview';

export interface AboutUsMissionPage {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    Overview: TitleAndDescription;
    Vision?: TitleAndDescription;
    Transformation: Overview;
    Quote?: string;
    Values?: TitleAndDescription;
  };
}
export interface AboutUsMissionPage_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  Overview: TitleAndDescription_Plain;
  Vision?: TitleAndDescription_Plain;
  Transformation: Overview_Plain;
  Quote?: string;
  Values?: TitleAndDescription_Plain;
}

export interface AboutUsMissionPage_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  Overview: TitleAndDescription_NoRelations;
  Vision?: TitleAndDescription_NoRelations;
  Transformation: Overview_NoRelations;
  Quote?: string;
  Values?: TitleAndDescription_NoRelations;
}

export interface AboutUsMissionPage_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  Overview: TitleAndDescription_Plain;
  Vision?: TitleAndDescription_Plain;
  Transformation: Overview_Plain;
  Quote?: string;
  Values?: TitleAndDescription_Plain;
}
