// Interface automatically generated by schemas-to-ts

import { Job } from '../../../job/content-types/job/job';
import { Media } from '../../../../common/schemas-to-ts/Media';
import { Job_Plain } from '../../../job/content-types/job/job';
import { Media_Plain } from '../../../../common/schemas-to-ts/Media';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface JobApplication {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    _softDeletedAt?: Date;
    _softDeletedById?: number;
    _softDeletedByType?: string;
    status?: string;
    job?: { data: Job };
    resume: { data: Media };
    email: string;
    firstName: string;
    lastName: string;
    phoneNumber: any;
    message?: string;
  };
}
export interface JobApplication_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  _softDeletedAt?: Date;
  _softDeletedById?: number;
  _softDeletedByType?: string;
  status?: string;
  job?: Job_Plain;
  resume: Media_Plain;
  email: string;
  firstName: string;
  lastName: string;
  phoneNumber: any;
  message?: string;
}

export interface JobApplication_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  _softDeletedAt?: Date;
  _softDeletedById?: number;
  _softDeletedByType?: string;
  status?: string;
  job?: number;
  resume: number;
  email: string;
  firstName: string;
  lastName: string;
  phoneNumber: any;
  message?: string;
}

export interface JobApplication_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  _softDeletedAt?: Date;
  _softDeletedById?: number;
  _softDeletedByType?: string;
  status?: string;
  job?: AdminPanelRelationPropertyModification<Job_Plain>;
  resume: AdminPanelRelationPropertyModification<Media_Plain>;
  email: string;
  firstName: string;
  lastName: string;
  phoneNumber: any;
  message?: string;
}
