// Interface automatically generated by schemas-to-ts

import { Job } from '../../../job/content-types/job/job';
import { User } from '../../../../common/schemas-to-ts/User';
import { Media } from '../../../../common/schemas-to-ts/Media';
import { Job_Plain } from '../../../job/content-types/job/job';
import { User_Plain } from '../../../../common/schemas-to-ts/User';
import { Media_Plain } from '../../../../common/schemas-to-ts/Media';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface JobApplication {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    status?: string;
    job?: { data: Job };
    applicant?: { data: User };
    resume: { data: Media };
    _softDeletedAt?: Date;
    _softDeletedById?: number;
    _softDeletedByType?: string;
  };
}
export interface JobApplication_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  status?: string;
  job?: Job_Plain;
  applicant?: User_Plain;
  resume: Media_Plain;
  _softDeletedAt?: Date;
  _softDeletedById?: number;
  _softDeletedByType?: string;
}

export interface JobApplication_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  status?: string;
  job?: number;
  applicant?: number;
  resume: number;
  _softDeletedAt?: Date;
  _softDeletedById?: number;
  _softDeletedByType?: string;
}

export interface JobApplication_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  status?: string;
  job?: AdminPanelRelationPropertyModification<Job_Plain>;
  applicant?: AdminPanelRelationPropertyModification<User_Plain>;
  resume: AdminPanelRelationPropertyModification<Media_Plain>;
  _softDeletedAt?: Date;
  _softDeletedById?: number;
  _softDeletedByType?: string;
}
