// Interface automatically generated by schemas-to-ts

import { Media } from '../../../../common/schemas-to-ts/Media';
import { Project } from '../../../project/content-types/project/project';
import { Media_Plain } from '../../../../common/schemas-to-ts/Media';
import { Project_Plain } from '../../../project/content-types/project/project';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export enum Category {
  Industries = 'Industries',
  Services = 'Services',}

export interface Expertise {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    _softDeletedAt?: Date;
    _softDeletedById?: number;
    _softDeletedByType?: string;
    name: string;
    title: string;
    description: string;
    mediaBanner?: { data: Media };
    projects: { data: Project[] };
    slug: string;
    banner: { data: Media };
    category: Category;
  };
}
export interface Expertise_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  _softDeletedAt?: Date;
  _softDeletedById?: number;
  _softDeletedByType?: string;
  name: string;
  title: string;
  description: string;
  mediaBanner?: Media_Plain;
  projects: Project_Plain[];
  slug: string;
  banner: Media_Plain;
  category: Category;
}

export interface Expertise_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  _softDeletedAt?: Date;
  _softDeletedById?: number;
  _softDeletedByType?: string;
  name: string;
  title: string;
  description: string;
  mediaBanner?: number;
  projects: number[];
  slug: string;
  banner: number;
  category: Category;
}

export interface Expertise_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  _softDeletedAt?: Date;
  _softDeletedById?: number;
  _softDeletedByType?: string;
  name: string;
  title: string;
  description: string;
  mediaBanner?: AdminPanelRelationPropertyModification<Media_Plain>;
  projects: AdminPanelRelationPropertyModification<Project_Plain>;
  slug: string;
  banner: AdminPanelRelationPropertyModification<Media_Plain>;
  category: Category;
}
