// Interface automatically generated by schemas-to-ts

import { Media } from '../../../../common/schemas-to-ts/Media';
import { Url } from '../../../../components/elements/interfaces/Url';
import { Media_Plain } from '../../../../common/schemas-to-ts/Media';
import { Url_Plain } from '../../../../components/elements/interfaces/Url';
import { Url_NoRelations } from '../../../../components/elements/interfaces/Url';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export enum Type {
  Kenyan = 'Kenyan',
  International = 'International',
  Other = 'Other',}

export interface Client {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    _softDeletedAt?: Date;
    _softDeletedById?: number;
    _softDeletedByType?: string;
    logo: { data: Media };
    url?: Url;
    name: string;
    slug?: string;
    countOfServicesProvided?: number;
    Type: Type;
  };
}
export interface Client_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  _softDeletedAt?: Date;
  _softDeletedById?: number;
  _softDeletedByType?: string;
  logo: Media_Plain;
  url?: Url_Plain;
  name: string;
  slug?: string;
  countOfServicesProvided?: number;
  Type: Type;
}

export interface Client_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  _softDeletedAt?: Date;
  _softDeletedById?: number;
  _softDeletedByType?: string;
  logo: number;
  url?: Url_NoRelations;
  name: string;
  slug?: string;
  countOfServicesProvided?: number;
  Type: Type;
}

export interface Client_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  _softDeletedAt?: Date;
  _softDeletedById?: number;
  _softDeletedByType?: string;
  logo: AdminPanelRelationPropertyModification<Media_Plain>;
  url?: Url_Plain;
  name: string;
  slug?: string;
  countOfServicesProvided?: number;
  Type: Type;
}
