// Interface automatically generated by schemas-to-ts

import { Hero } from '../../../../components/sections/interfaces/Hero';
import { Overview } from '../../../../components/sections/interfaces/Overview';
import { Person } from '../../../person/content-types/person/person';
import { PersonQuote } from '../../../../components/elements/interfaces/PersonQuote';
import { Media } from '../../../../common/schemas-to-ts/Media';
import { Hero_Plain } from '../../../../components/sections/interfaces/Hero';
import { Overview_Plain } from '../../../../components/sections/interfaces/Overview';
import { Person_Plain } from '../../../person/content-types/person/person';
import { PersonQuote_Plain } from '../../../../components/elements/interfaces/PersonQuote';
import { Media_Plain } from '../../../../common/schemas-to-ts/Media';
import { Hero_NoRelations } from '../../../../components/sections/interfaces/Hero';
import { Overview_NoRelations } from '../../../../components/sections/interfaces/Overview';
import { PersonQuote_NoRelations } from '../../../../components/elements/interfaces/PersonQuote';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export enum Type {
  Article = 'Article',
  Publication = 'Publication',
  Study = 'Study',
  Topic = 'Topic',}

export interface Insight {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    _softDeletedAt?: Date;
    _softDeletedById?: number;
    _softDeletedByType?: string;
    Hero: Hero;
    Overview: Overview;
    Name: string;
    slug: string;
    people: { data: Person[] };
    Body: string;
    Type: Type;
    AuthorQuote: PersonQuote[];
    Image: { data: Media };
    RelatedInsights: { data: Insight[] };
  };
}
export interface Insight_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  _softDeletedAt?: Date;
  _softDeletedById?: number;
  _softDeletedByType?: string;
  Hero: Hero_Plain;
  Overview: Overview_Plain;
  Name: string;
  slug: string;
  people: Person_Plain[];
  Body: string;
  Type: Type;
  AuthorQuote: PersonQuote_Plain[];
  Image: Media_Plain;
  RelatedInsights: Insight_Plain[];
}

export interface Insight_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  _softDeletedAt?: Date;
  _softDeletedById?: number;
  _softDeletedByType?: string;
  Hero: Hero_NoRelations;
  Overview: Overview_NoRelations;
  Name: string;
  slug: string;
  people: number[];
  Body: string;
  Type: Type;
  AuthorQuote: PersonQuote_NoRelations[];
  Image: number;
  RelatedInsights: number[];
}

export interface Insight_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  _softDeletedAt?: Date;
  _softDeletedById?: number;
  _softDeletedByType?: string;
  Hero: Hero_Plain;
  Overview: Overview_Plain;
  Name: string;
  slug: string;
  people: AdminPanelRelationPropertyModification<Person_Plain>;
  Body: string;
  Type: Type;
  AuthorQuote: PersonQuote_Plain[];
  Image: AdminPanelRelationPropertyModification<Media_Plain>;
  RelatedInsights: AdminPanelRelationPropertyModification<Insight_Plain>;
}
