// Interface automatically generated by schemas-to-ts

import { Media } from '../../../common/schemas-to-ts/Media';
import { Media_Plain } from '../../../common/schemas-to-ts/Media';

export interface Banner {
  banner: { data: Media };
  description: string;
}
export interface Banner_Plain {
  banner: Media_Plain;
  description: string;
}

export interface Banner_NoRelations {
  banner: number;
  description: string;
}

