// Interface automatically generated by schemas-to-ts

import { Card } from '../../elements/interfaces/Card';
import { Card_Plain } from '../../elements/interfaces/Card';
import { Card_NoRelations } from '../../elements/interfaces/Card';

export interface CardGrid {
  title?: string;
  cards: Card[];
}
export interface CardGrid_Plain {
  title?: string;
  cards: Card_Plain[];
}

export interface CardGrid_NoRelations {
  title?: string;
  cards: Card_NoRelations[];
}

