// Interface automatically generated by schemas-to-ts

export interface Hero {
  title?: string;
}
export interface Hero_Plain {
  title?: string;
}

export interface Hero_NoRelations {
  title?: string;
}

