// Interface automatically generated by schemas-to-ts

import { Media } from '../../../common/schemas-to-ts/Media';
import { ButtonLink } from '../../links/interfaces/ButtonLink';
import { Media_Plain } from '../../../common/schemas-to-ts/Media';
import { ButtonLink_Plain } from '../../links/interfaces/ButtonLink';
import { ButtonLink_NoRelations } from '../../links/interfaces/ButtonLink';

export interface Hero {
  picture: { data: Media };
  callToAction?: ButtonLink;
  logo?: { data: Media };
}
export interface Hero_Plain {
  picture: Media_Plain;
  callToAction?: ButtonLink_Plain;
  logo?: Media_Plain;
}

export interface Hero_NoRelations {
  picture: number;
  callToAction?: ButtonLink_NoRelations;
  logo?: number;
}

