// Interface automatically generated by schemas-to-ts

import { Media } from '../../../common/schemas-to-ts/Media';
import { Media_Plain } from '../../../common/schemas-to-ts/Media';

export interface LargeVideo {
  title?: string;
  description?: string;
  video: { data: Media };
  poster?: { data: Media };
}
export interface LargeVideo_Plain {
  title?: string;
  description?: string;
  video: Media_Plain;
  poster?: Media_Plain;
}

export interface LargeVideo_NoRelations {
  title?: string;
  description?: string;
  video: number;
  poster?: number;
}

