// Interface automatically generated by schemas-to-ts

import { Media } from '../../../common/schemas-to-ts/Media';
import { Media_Plain } from '../../../common/schemas-to-ts/Media';

export interface Overview {
  Title: string;
  Image?: { data: Media };
  description?: string;
}
export interface Overview_Plain {
  Title: string;
  Image?: Media_Plain;
  description?: string;
}

export interface Overview_NoRelations {
  Title: string;
  Image?: number;
  description?: string;
}

