// Interface automatically generated by schemas-to-ts

import { Person } from '../../../api/person/content-types/person/person';
import { Person_Plain } from '../../../api/person/content-types/person/person';

export interface PeopleGroupRow {
  GroupTitle: string;
  people: { data: Person[] };
}
export interface PeopleGroupRow_Plain {
  GroupTitle: string;
  people: Person_Plain[];
}

export interface PeopleGroupRow_NoRelations {
  GroupTitle: string;
  people: number[];
}

