// Interface automatically generated by schemas-to-ts

import { Link } from '../../links/interfaces/Link';
import { Logos } from '../../elements/interfaces/Logos';
import { Testimonial } from '../../elements/interfaces/Testimonial';
import { Link_Plain } from '../../links/interfaces/Link';
import { Logos_Plain } from '../../elements/interfaces/Logos';
import { Testimonial_Plain } from '../../elements/interfaces/Testimonial';
import { Link_NoRelations } from '../../links/interfaces/Link';
import { Logos_NoRelations } from '../../elements/interfaces/Logos';
import { Testimonial_NoRelations } from '../../elements/interfaces/Testimonial';

export interface TestimonialsGroup {
  title?: string;
  description?: string;
  link?: Link;
  logos: Logos[];
  testimonials: Testimonial[];
}
export interface TestimonialsGroup_Plain {
  title?: string;
  description?: string;
  link?: Link_Plain;
  logos: Logos_Plain[];
  testimonials: Testimonial_Plain[];
}

export interface TestimonialsGroup_NoRelations {
  title?: string;
  description?: string;
  link?: Link_NoRelations;
  logos: Logos_NoRelations[];
  testimonials: Testimonial_NoRelations[];
}

