// Interface automatically generated by schemas-to-ts

export interface TitleAndDescription {
  Title: string;
  Description: string;
}
export interface TitleAndDescription_Plain {
  Title: string;
  Description: string;
}

export interface TitleAndDescription_NoRelations {
  Title: string;
  Description: string;
}

