// Interface automatically generated by schemas-to-ts

import { Media } from '../../../common/schemas-to-ts/Media';
import { FooterSection } from '../../elements/interfaces/FooterSection';
import { Media_Plain } from '../../../common/schemas-to-ts/Media';
import { FooterSection_Plain } from '../../elements/interfaces/FooterSection';
import { FooterSection_NoRelations } from '../../elements/interfaces/FooterSection';

export interface Footer {
  logo?: { data: Media };
  columns: FooterSection[];
  smallText?: string;
}
export interface Footer_Plain {
  logo?: Media_Plain;
  columns: FooterSection_Plain[];
  smallText?: string;
}

export interface Footer_NoRelations {
  logo?: number;
  columns: FooterSection_NoRelations[];
  smallText?: string;
}

