// Interface automatically generated by schemas-to-ts

import { Link } from '../../links/interfaces/Link';
import { ButtonLink } from '../../links/interfaces/ButtonLink';
import { Media } from '../../../common/schemas-to-ts/Media';
import { Link_Plain } from '../../links/interfaces/Link';
import { ButtonLink_Plain } from '../../links/interfaces/ButtonLink';
import { Media_Plain } from '../../../common/schemas-to-ts/Media';
import { Link_NoRelations } from '../../links/interfaces/Link';
import { ButtonLink_NoRelations } from '../../links/interfaces/ButtonLink';

export interface Navbar {
  links: Link[];
  button?: ButtonLink;
  logo: { data: Media };
}
export interface Navbar_Plain {
  links: Link_Plain[];
  button?: ButtonLink_Plain;
  logo: Media_Plain;
}

export interface Navbar_NoRelations {
  links: Link_NoRelations[];
  button?: ButtonLink_NoRelations;
  logo: number;
}

