// Interface automatically generated by schemas-to-ts

export interface SocialMediaLink {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    title: string;
    url: string;
    slug: string;
  };
}
export interface SocialMediaLink_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title: string;
  url: string;
  slug: string;
}

export interface SocialMediaLink_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title: string;
  url: string;
  slug: string;
}

export interface SocialMediaLink_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title: string;
  url: string;
  slug: string;
}
