// Interface automatically generated by schemas-to-ts

import { Hero } from '../../../../components/sections/interfaces/Hero';
import { Overview } from '../../../../components/sections/interfaces/Overview';
import { Media } from '../../../../common/schemas-to-ts/Media';
import { Hero_Plain } from '../../../../components/sections/interfaces/Hero';
import { Overview_Plain } from '../../../../components/sections/interfaces/Overview';
import { Media_Plain } from '../../../../common/schemas-to-ts/Media';
import { Hero_NoRelations } from '../../../../components/sections/interfaces/Hero';
import { Overview_NoRelations } from '../../../../components/sections/interfaces/Overview';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Approach {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    Hero?: Hero;
    Overview?: Overview;
    body: string;
    mediaBanner?: { data: Media };
  };
}
export interface Approach_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  Hero?: Hero_Plain;
  Overview?: Overview_Plain;
  body: string;
  mediaBanner?: Media_Plain;
}

export interface Approach_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  Hero?: Hero_NoRelations;
  Overview?: Overview_NoRelations;
  body: string;
  mediaBanner?: number;
}

export interface Approach_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  Hero?: Hero_Plain;
  Overview?: Overview_Plain;
  body: string;
  mediaBanner?: AdminPanelRelationPropertyModification<Media_Plain>;
}
