// Interface automatically generated by schemas-to-ts

import { Hero } from '../../../../components/sections/interfaces/Hero';
import { Overview } from '../../../../components/sections/interfaces/Overview';
import { Banner } from '../../../../components/sections/interfaces/Banner';
import { CardGrid } from '../../../../components/sections/interfaces/CardGrid';
import { Hero_Plain } from '../../../../components/sections/interfaces/Hero';
import { Overview_Plain } from '../../../../components/sections/interfaces/Overview';
import { Banner_Plain } from '../../../../components/sections/interfaces/Banner';
import { CardGrid_Plain } from '../../../../components/sections/interfaces/CardGrid';
import { Hero_NoRelations } from '../../../../components/sections/interfaces/Hero';
import { Overview_NoRelations } from '../../../../components/sections/interfaces/Overview';
import { Banner_NoRelations } from '../../../../components/sections/interfaces/Banner';
import { CardGrid_NoRelations } from '../../../../components/sections/interfaces/CardGrid';

export interface Approach {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    _softDeletedAt?: Date;
    _softDeletedById?: number;
    _softDeletedByType?: string;
    Hero?: Hero;
    Overview?: Overview;
    body: string;
    banner?: Banner;
    quote: string;
    clientFocus: CardGrid;
  };
}
export interface Approach_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  _softDeletedAt?: Date;
  _softDeletedById?: number;
  _softDeletedByType?: string;
  Hero?: Hero_Plain;
  Overview?: Overview_Plain;
  body: string;
  banner?: Banner_Plain;
  quote: string;
  clientFocus: CardGrid_Plain;
}

export interface Approach_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  _softDeletedAt?: Date;
  _softDeletedById?: number;
  _softDeletedByType?: string;
  Hero?: Hero_NoRelations;
  Overview?: Overview_NoRelations;
  body: string;
  banner?: Banner_NoRelations;
  quote: string;
  clientFocus: CardGrid_NoRelations;
}

export interface Approach_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  _softDeletedAt?: Date;
  _softDeletedById?: number;
  _softDeletedByType?: string;
  Hero?: Hero_Plain;
  Overview?: Overview_Plain;
  body: string;
  banner?: Banner_Plain;
  quote: string;
  clientFocus: CardGrid_Plain;
}
