// Interface automatically generated by schemas-to-ts

import { Media } from '../../../common/schemas-to-ts/Media';
import { Media_Plain } from '../../../common/schemas-to-ts/Media';

export enum TwitterCardType {
  Summary = 'summary',
  SummaryLargeImage = 'summary_large_image',
  App = 'app',
  Player = 'player',}

export interface Metadata {
  metaTitle: string;
  metaDescription: string;
  shareImage?: { data: Media };
  twitterCardType?: TwitterCardType;
  twitterUsername?: string;
}
export interface Metadata_Plain {
  metaTitle: string;
  metaDescription: string;
  shareImage?: Media_Plain;
  twitterCardType?: TwitterCardType;
  twitterUsername?: string;
}

export interface Metadata_NoRelations {
  metaTitle: string;
  metaDescription: string;
  shareImage?: number;
  twitterCardType?: TwitterCardType;
  twitterUsername?: string;
}

