// Interface automatically generated by schemas-to-ts

import { JobApplication } from '../../../job-application/content-types/job-application/job-application';
import { JobApplication_Plain } from '../../../job-application/content-types/job-application/job-application';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export enum Type {
  PermanentFullTime = 'Permanent Full Time',
  PermanentPartTime = 'Permanent Part Time',
  TemporaryFullTime = 'Temporary Full Time',
  TemporaryPartTime = 'Temporary Part Time',}

export interface Job {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    name: string;
    description: string;
    available: boolean;
    type: Type;
    department: string;
    responsibilities: string;
    requirements: string;
    location: string;
    closingDate: Date;
    slug: string;
    salary?: number;
    _softDeletedAt?: Date;
    _softDeletedById?: number;
    _softDeletedByType?: string;
    job_applications: { data: JobApplication[] };
  };
}
export interface Job_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name: string;
  description: string;
  available: boolean;
  type: Type;
  department: string;
  responsibilities: string;
  requirements: string;
  location: string;
  closingDate: Date;
  slug: string;
  salary?: number;
  _softDeletedAt?: Date;
  _softDeletedById?: number;
  _softDeletedByType?: string;
  job_applications: JobApplication_Plain[];
}

export interface Job_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name: string;
  description: string;
  available: boolean;
  type: Type;
  department: string;
  responsibilities: string;
  requirements: string;
  location: string;
  closingDate: Date;
  slug: string;
  salary?: number;
  _softDeletedAt?: Date;
  _softDeletedById?: number;
  _softDeletedByType?: string;
  job_applications: number[];
}

export interface Job_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name: string;
  description: string;
  available: boolean;
  type: Type;
  department: string;
  responsibilities: string;
  requirements: string;
  location: string;
  closingDate: Date;
  slug: string;
  salary?: number;
  _softDeletedAt?: Date;
  _softDeletedById?: number;
  _softDeletedByType?: string;
  job_applications: AdminPanelRelationPropertyModification<JobApplication_Plain>;
}
