// Interface automatically generated by schemas-to-ts

import { JobApplication } from '../../../job-application/content-types/job-application/job-application';
import { Jobadvert } from '../../../jobadvert/content-types/jobadvert/jobadvert';
import { JobApplication_Plain } from '../../../job-application/content-types/job-application/job-application';
import { Jobadvert_Plain } from '../../../jobadvert/content-types/jobadvert/jobadvert';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export enum Type {
  PermanentFullTime = 'Permanent Full Time',
  PermanentPartTime = 'Permanent Part Time',
  TemporaryFullTime = 'Temporary Full Time',
  TemporaryPartTime = 'Temporary Part Time',}

export interface Job {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    _softDeletedAt?: Date;
    _softDeletedById?: number;
    _softDeletedByType?: string;
    name: string;
    description: string;
    available: boolean;
    type: Type;
    department: string;
    responsibilities: string;
    requirements: string;
    location: string;
    closingDate: Date;
    slug: string;
    salary?: number;
    job_applications: { data: JobApplication[] };
    level: string;
    jobSpecifications?: string;
    personSpecifications?: string;
    keyCompetenciesAndSkills?: string;
    termsOfService?: string;
    howToApply?: string;
    applyOnline?: boolean;
    jobAdvert?: { data: Jobadvert };
  };
}
export interface Job_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  _softDeletedAt?: Date;
  _softDeletedById?: number;
  _softDeletedByType?: string;
  name: string;
  description: string;
  available: boolean;
  type: Type;
  department: string;
  responsibilities: string;
  requirements: string;
  location: string;
  closingDate: Date;
  slug: string;
  salary?: number;
  job_applications: JobApplication_Plain[];
  level: string;
  jobSpecifications?: string;
  personSpecifications?: string;
  keyCompetenciesAndSkills?: string;
  termsOfService?: string;
  howToApply?: string;
  applyOnline?: boolean;
  jobAdvert?: Jobadvert_Plain;
}

export interface Job_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  _softDeletedAt?: Date;
  _softDeletedById?: number;
  _softDeletedByType?: string;
  name: string;
  description: string;
  available: boolean;
  type: Type;
  department: string;
  responsibilities: string;
  requirements: string;
  location: string;
  closingDate: Date;
  slug: string;
  salary?: number;
  job_applications: number[];
  level: string;
  jobSpecifications?: string;
  personSpecifications?: string;
  keyCompetenciesAndSkills?: string;
  termsOfService?: string;
  howToApply?: string;
  applyOnline?: boolean;
  jobAdvert?: number;
}

export interface Job_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  _softDeletedAt?: Date;
  _softDeletedById?: number;
  _softDeletedByType?: string;
  name: string;
  description: string;
  available: boolean;
  type: Type;
  department: string;
  responsibilities: string;
  requirements: string;
  location: string;
  closingDate: Date;
  slug: string;
  salary?: number;
  job_applications: AdminPanelRelationPropertyModification<JobApplication_Plain>;
  level: string;
  jobSpecifications?: string;
  personSpecifications?: string;
  keyCompetenciesAndSkills?: string;
  termsOfService?: string;
  howToApply?: string;
  applyOnline?: boolean;
  jobAdvert?: AdminPanelRelationPropertyModification<Jobadvert_Plain>;
}
