// Interface automatically generated by schemas-to-ts

import { Hero } from '../../../../components/sections/interfaces/Hero';
import { Overview } from '../../../../components/sections/interfaces/Overview';
import { Media } from '../../../../common/schemas-to-ts/Media';
import { Hero_Plain } from '../../../../components/sections/interfaces/Hero';
import { Overview_Plain } from '../../../../components/sections/interfaces/Overview';
import { Media_Plain } from '../../../../common/schemas-to-ts/Media';
import { Hero_NoRelations } from '../../../../components/sections/interfaces/Hero';
import { Overview_NoRelations } from '../../../../components/sections/interfaces/Overview';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface AboutUsWhoWeAre {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    _softDeletedAt?: Date;
    _softDeletedById?: number;
    _softDeletedByType?: string;
    Hero: Hero;
    Overview: Overview;
    MediaBanner?: { data: Media };
    Body: string;
  };
}
export interface AboutUsWhoWeAre_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  _softDeletedAt?: Date;
  _softDeletedById?: number;
  _softDeletedByType?: string;
  Hero: Hero_Plain;
  Overview: Overview_Plain;
  MediaBanner?: Media_Plain;
  Body: string;
}

export interface AboutUsWhoWeAre_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  _softDeletedAt?: Date;
  _softDeletedById?: number;
  _softDeletedByType?: string;
  Hero: Hero_NoRelations;
  Overview: Overview_NoRelations;
  MediaBanner?: number;
  Body: string;
}

export interface AboutUsWhoWeAre_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  _softDeletedAt?: Date;
  _softDeletedById?: number;
  _softDeletedByType?: string;
  Hero: Hero_Plain;
  Overview: Overview_Plain;
  MediaBanner?: AdminPanelRelationPropertyModification<Media_Plain>;
  Body: string;
}
