// Interface automatically generated by schemas-to-ts

import { Hero } from '../../../../components/sections/interfaces/Hero';
import { Overview } from '../../../../components/sections/interfaces/Overview';
import { Hero_Plain } from '../../../../components/sections/interfaces/Hero';
import { Overview_Plain } from '../../../../components/sections/interfaces/Overview';
import { Hero_NoRelations } from '../../../../components/sections/interfaces/Hero';
import { Overview_NoRelations } from '../../../../components/sections/interfaces/Overview';

export interface TheNeed {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    _softDeletedAt?: Date;
    _softDeletedById?: number;
    _softDeletedByType?: string;
    Hero: Hero;
    Overview?: Overview;
    body: string;
  };
}
export interface TheNeed_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  _softDeletedAt?: Date;
  _softDeletedById?: number;
  _softDeletedByType?: string;
  Hero: Hero_Plain;
  Overview?: Overview_Plain;
  body: string;
}

export interface TheNeed_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  _softDeletedAt?: Date;
  _softDeletedById?: number;
  _softDeletedByType?: string;
  Hero: Hero_NoRelations;
  Overview?: Overview_NoRelations;
  body: string;
}

export interface TheNeed_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  _softDeletedAt?: Date;
  _softDeletedById?: number;
  _softDeletedByType?: string;
  Hero: Hero_Plain;
  Overview?: Overview_Plain;
  body: string;
}
