// Interface automatically generated by schemas-to-ts

import { TitleAndDescription } from '../../../../components/sections/interfaces/TitleAndDescription';
import { Overview } from '../../../../components/sections/interfaces/Overview';
import { Hero } from '../../../../components/sections/interfaces/Hero';
import { TitleAndDescription_Plain } from '../../../../components/sections/interfaces/TitleAndDescription';
import { Overview_Plain } from '../../../../components/sections/interfaces/Overview';
import { Hero_Plain } from '../../../../components/sections/interfaces/Hero';
import { TitleAndDescription_NoRelations } from '../../../../components/sections/interfaces/TitleAndDescription';
import { Overview_NoRelations } from '../../../../components/sections/interfaces/Overview';
import { Hero_NoRelations } from '../../../../components/sections/interfaces/Hero';

export interface BusinessAgilityAndContinuityPage {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    _softDeletedAt?: Date;
    _softDeletedById?: number;
    _softDeletedByType?: string;
    Description?: TitleAndDescription;
    Overview?: TitleAndDescription;
    ValueProposition?: Overview;
    Guidelines?: TitleAndDescription;
    Quote?: string;
    BuildResilience?: TitleAndDescription;
    DigitalDiscipline?: Overview;
    Hero?: Hero;
  };
}
export interface BusinessAgilityAndContinuityPage_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  _softDeletedAt?: Date;
  _softDeletedById?: number;
  _softDeletedByType?: string;
  Description?: TitleAndDescription_Plain;
  Overview?: TitleAndDescription_Plain;
  ValueProposition?: Overview_Plain;
  Guidelines?: TitleAndDescription_Plain;
  Quote?: string;
  BuildResilience?: TitleAndDescription_Plain;
  DigitalDiscipline?: Overview_Plain;
  Hero?: Hero_Plain;
}

export interface BusinessAgilityAndContinuityPage_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  _softDeletedAt?: Date;
  _softDeletedById?: number;
  _softDeletedByType?: string;
  Description?: TitleAndDescription_NoRelations;
  Overview?: TitleAndDescription_NoRelations;
  ValueProposition?: Overview_NoRelations;
  Guidelines?: TitleAndDescription_NoRelations;
  Quote?: string;
  BuildResilience?: TitleAndDescription_NoRelations;
  DigitalDiscipline?: Overview_NoRelations;
  Hero?: Hero_NoRelations;
}

export interface BusinessAgilityAndContinuityPage_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  _softDeletedAt?: Date;
  _softDeletedById?: number;
  _softDeletedByType?: string;
  Description?: TitleAndDescription_Plain;
  Overview?: TitleAndDescription_Plain;
  ValueProposition?: Overview_Plain;
  Guidelines?: TitleAndDescription_Plain;
  Quote?: string;
  BuildResilience?: TitleAndDescription_Plain;
  DigitalDiscipline?: Overview_Plain;
  Hero?: Hero_Plain;
}
