// Interface automatically generated by schemas-to-ts

import { Hero } from '../../../../components/sections/interfaces/Hero';
import { TitleAndDescription } from '../../../../components/sections/interfaces/TitleAndDescription';
import { Overview } from '../../../../components/sections/interfaces/Overview';
import { Person } from '../../../person/content-types/person/person';
import { Media } from '../../../../common/schemas-to-ts/Media';
import { Hero_Plain } from '../../../../components/sections/interfaces/Hero';
import { TitleAndDescription_Plain } from '../../../../components/sections/interfaces/TitleAndDescription';
import { Overview_Plain } from '../../../../components/sections/interfaces/Overview';
import { Person_Plain } from '../../../person/content-types/person/person';
import { Media_Plain } from '../../../../common/schemas-to-ts/Media';
import { Hero_NoRelations } from '../../../../components/sections/interfaces/Hero';
import { TitleAndDescription_NoRelations } from '../../../../components/sections/interfaces/TitleAndDescription';
import { Overview_NoRelations } from '../../../../components/sections/interfaces/Overview';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface LeadershipPage {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    _softDeletedAt?: Date;
    _softDeletedById?: number;
    _softDeletedByType?: string;
    Hero?: Hero;
    Description: TitleAndDescription;
    Overview: TitleAndDescription;
    BusinessAndContinuity: TitleAndDescription;
    HowWeWork?: Overview;
    Quote?: string;
    WhatWeDo: Overview;
    team: { data: Person[] };
    Framework?: { data: Media };
  };
}
export interface LeadershipPage_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  _softDeletedAt?: Date;
  _softDeletedById?: number;
  _softDeletedByType?: string;
  Hero?: Hero_Plain;
  Description: TitleAndDescription_Plain;
  Overview: TitleAndDescription_Plain;
  BusinessAndContinuity: TitleAndDescription_Plain;
  HowWeWork?: Overview_Plain;
  Quote?: string;
  WhatWeDo: Overview_Plain;
  team: Person_Plain[];
  Framework?: Media_Plain;
}

export interface LeadershipPage_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  _softDeletedAt?: Date;
  _softDeletedById?: number;
  _softDeletedByType?: string;
  Hero?: Hero_NoRelations;
  Description: TitleAndDescription_NoRelations;
  Overview: TitleAndDescription_NoRelations;
  BusinessAndContinuity: TitleAndDescription_NoRelations;
  HowWeWork?: Overview_NoRelations;
  Quote?: string;
  WhatWeDo: Overview_NoRelations;
  team: number[];
  Framework?: number;
}

export interface LeadershipPage_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  _softDeletedAt?: Date;
  _softDeletedById?: number;
  _softDeletedByType?: string;
  Hero?: Hero_Plain;
  Description: TitleAndDescription_Plain;
  Overview: TitleAndDescription_Plain;
  BusinessAndContinuity: TitleAndDescription_Plain;
  HowWeWork?: Overview_Plain;
  Quote?: string;
  WhatWeDo: Overview_Plain;
  team: AdminPanelRelationPropertyModification<Person_Plain>;
  Framework?: AdminPanelRelationPropertyModification<Media_Plain>;
}
