// Interface automatically generated by schemas-to-ts

import { Media } from '../../../common/schemas-to-ts/Media';
import { Url } from './Url';
import { Media_Plain } from '../../../common/schemas-to-ts/Media';
import { Url_Plain } from './Url';
import { Url_NoRelations } from './Url';

export interface Card {
  title: string;
  description?: string;
  picture: { data: Media };
  url?: Url;
  tag?: string;
}
export interface Card_Plain {
  title: string;
  description?: string;
  picture: Media_Plain;
  url?: Url_Plain;
  tag?: string;
}

export interface Card_NoRelations {
  title: string;
  description?: string;
  picture: number;
  url?: Url_NoRelations;
  tag?: string;
}

