// Interface automatically generated by schemas-to-ts

import { Media } from '../../../common/schemas-to-ts/Media';
import { Media_Plain } from '../../../common/schemas-to-ts/Media';

export interface FeatureColumn {
  title: string;
  description?: string;
  icon: { data: Media };
}
export interface FeatureColumn_Plain {
  title: string;
  description?: string;
  icon: Media_Plain;
}

export interface FeatureColumn_NoRelations {
  title: string;
  description?: string;
  icon: number;
}

