// Interface automatically generated by schemas-to-ts

export interface Feature {
  name?: string;
}
export interface Feature_Plain {
  name?: string;
}

export interface Feature_NoRelations {
  name?: string;
}

