// Interface automatically generated by schemas-to-ts

export interface LabelAndText {
  Label: string;
  Text: string;
}
export interface LabelAndText_Plain {
  Label: string;
  Text: string;
}

export interface LabelAndText_NoRelations {
  Label: string;
  Text: string;
}

