// Interface automatically generated by schemas-to-ts

import { Media } from '../../../common/schemas-to-ts/Media';
import { Media_Plain } from '../../../common/schemas-to-ts/Media';

export interface Logos {
  title?: string;
  logo?: { data: Media };
}
export interface Logos_Plain {
  title?: string;
  logo?: Media_Plain;
}

export interface Logos_NoRelations {
  title?: string;
  logo?: number;
}

