// Interface automatically generated by schemas-to-ts

export enum Type {
  Alert = 'alert',
  Info = 'info',
  Warning = 'warning',}

export interface NotificationBanner {
  text?: string;
  type: Type;
}
export interface NotificationBanner_Plain {
  text?: string;
  type: Type;
}

export interface NotificationBanner_NoRelations {
  text?: string;
  type: Type;
}

