// Interface automatically generated by schemas-to-ts

import { Person } from '../../../api/person/content-types/person/person';
import { Person_Plain } from '../../../api/person/content-types/person/person';

export interface PersonQuote {
  Person?: { data: Person };
  Quote: string;
}
export interface PersonQuote_Plain {
  Person?: Person_Plain;
  Quote: string;
}

export interface PersonQuote_NoRelations {
  Person?: number;
  Quote: string;
}

