// Interface automatically generated by schemas-to-ts

import { Feature } from './Feature';
import { Feature_Plain } from './Feature';
import { Feature_NoRelations } from './Feature';

export interface Plan {
  name?: string;
  description?: string;
  features: Feature[];
  isRecommended?: boolean;
  price?: number;
  pricePeriod?: string;
}
export interface Plan_Plain {
  name?: string;
  description?: string;
  features: Feature_Plain[];
  isRecommended?: boolean;
  price?: number;
  pricePeriod?: string;
}

export interface Plan_NoRelations {
  name?: string;
  description?: string;
  features: Feature_NoRelations[];
  isRecommended?: boolean;
  price?: number;
  pricePeriod?: string;
}

