// Interface automatically generated by schemas-to-ts

import { Media } from '../../../common/schemas-to-ts/Media';
import { Media_Plain } from '../../../common/schemas-to-ts/Media';

export interface Testimonial {
  logo?: { data: Media };
  picture?: { data: Media };
  text?: string;
  authorName?: string;
  authorTitle?: string;
  link?: string;
}
export interface Testimonial_Plain {
  logo?: Media_Plain;
  picture?: Media_Plain;
  text?: string;
  authorName?: string;
  authorTitle?: string;
  link?: string;
}

export interface Testimonial_NoRelations {
  logo?: number;
  picture?: number;
  text?: string;
  authorName?: string;
  authorTitle?: string;
  link?: string;
}

