// Interface automatically generated by schemas-to-ts

export interface Url {
  value: string;
}
export interface Url_Plain {
  value: string;
}

export interface Url_NoRelations {
  value: string;
}

