// Interface automatically generated by schemas-to-ts

export interface ApplyOnline {
  visible?: boolean;
  link?: string;
}
export interface ApplyOnline_Plain {
  visible?: boolean;
  link?: string;
}

export interface ApplyOnline_NoRelations {
  visible?: boolean;
  link?: string;
}

