// Interface automatically generated by schemas-to-ts

import { Hero } from '../../../../components/sections/interfaces/Hero';
import { Overview } from '../../../../components/sections/interfaces/Overview';
import { TitleAndDescription } from '../../../../components/sections/interfaces/TitleAndDescription';
import { Media } from '../../../../common/schemas-to-ts/Media';
import { Hero_Plain } from '../../../../components/sections/interfaces/Hero';
import { Overview_Plain } from '../../../../components/sections/interfaces/Overview';
import { TitleAndDescription_Plain } from '../../../../components/sections/interfaces/TitleAndDescription';
import { Media_Plain } from '../../../../common/schemas-to-ts/Media';
import { Hero_NoRelations } from '../../../../components/sections/interfaces/Hero';
import { Overview_NoRelations } from '../../../../components/sections/interfaces/Overview';
import { TitleAndDescription_NoRelations } from '../../../../components/sections/interfaces/TitleAndDescription';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface LandValueCapture {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    _softDeletedAt?: Date;
    _softDeletedById?: number;
    _softDeletedByType?: string;
    Hero?: Hero;
    Background: Overview;
    Description: Overview;
    Benefits?: Overview;
    Overview?: TitleAndDescription;
    Case?: Overview;
    Report?: { data: Media };
  };
}
export interface LandValueCapture_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  _softDeletedAt?: Date;
  _softDeletedById?: number;
  _softDeletedByType?: string;
  Hero?: Hero_Plain;
  Background: Overview_Plain;
  Description: Overview_Plain;
  Benefits?: Overview_Plain;
  Overview?: TitleAndDescription_Plain;
  Case?: Overview_Plain;
  Report?: Media_Plain;
}

export interface LandValueCapture_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  _softDeletedAt?: Date;
  _softDeletedById?: number;
  _softDeletedByType?: string;
  Hero?: Hero_NoRelations;
  Background: Overview_NoRelations;
  Description: Overview_NoRelations;
  Benefits?: Overview_NoRelations;
  Overview?: TitleAndDescription_NoRelations;
  Case?: Overview_NoRelations;
  Report?: number;
}

export interface LandValueCapture_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  _softDeletedAt?: Date;
  _softDeletedById?: number;
  _softDeletedByType?: string;
  Hero?: Hero_Plain;
  Background: Overview_Plain;
  Description: Overview_Plain;
  Benefits?: Overview_Plain;
  Overview?: TitleAndDescription_Plain;
  Case?: Overview_Plain;
  Report?: AdminPanelRelationPropertyModification<Media_Plain>;
}
