// Interface automatically generated by schemas-to-ts

import { Hero } from '../../../../components/sections/interfaces/Hero';
import { Overview } from '../../../../components/sections/interfaces/Overview';
import { Project } from '../../../project/content-types/project/project';
import { Person } from '../../../person/content-types/person/person';
import { Card } from '../../../../components/elements/interfaces/Card';
import { Hero_Plain } from '../../../../components/sections/interfaces/Hero';
import { Overview_Plain } from '../../../../components/sections/interfaces/Overview';
import { Project_Plain } from '../../../project/content-types/project/project';
import { Person_Plain } from '../../../person/content-types/person/person';
import { Card_Plain } from '../../../../components/elements/interfaces/Card';
import { Hero_NoRelations } from '../../../../components/sections/interfaces/Hero';
import { Overview_NoRelations } from '../../../../components/sections/interfaces/Overview';
import { Card_NoRelations } from '../../../../components/elements/interfaces/Card';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Home {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    _softDeletedAt?: Date;
    _softDeletedById?: number;
    _softDeletedByType?: string;
    Hero: Hero;
    Overview?: Overview;
    Projects: { data: Project[] };
    people: { data: Person[] };
    JoinTheTeam: Card[];
  };
}
export interface Home_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  _softDeletedAt?: Date;
  _softDeletedById?: number;
  _softDeletedByType?: string;
  Hero: Hero_Plain;
  Overview?: Overview_Plain;
  Projects: Project_Plain[];
  people: Person_Plain[];
  JoinTheTeam: Card_Plain[];
}

export interface Home_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  _softDeletedAt?: Date;
  _softDeletedById?: number;
  _softDeletedByType?: string;
  Hero: Hero_NoRelations;
  Overview?: Overview_NoRelations;
  Projects: number[];
  people: number[];
  JoinTheTeam: Card_NoRelations[];
}

export interface Home_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  _softDeletedAt?: Date;
  _softDeletedById?: number;
  _softDeletedByType?: string;
  Hero: Hero_Plain;
  Overview?: Overview_Plain;
  Projects: AdminPanelRelationPropertyModification<Project_Plain>;
  people: AdminPanelRelationPropertyModification<Person_Plain>;
  JoinTheTeam: Card_Plain[];
}
