// Interface automatically generated by schemas-to-ts

import { Hero } from '../../../../components/sections/interfaces/Hero';
import { Overview } from '../../../../components/sections/interfaces/Overview';
import { Card } from '../../../../components/elements/interfaces/Card';
import { Hero_Plain } from '../../../../components/sections/interfaces/Hero';
import { Overview_Plain } from '../../../../components/sections/interfaces/Overview';
import { Card_Plain } from '../../../../components/elements/interfaces/Card';
import { Hero_NoRelations } from '../../../../components/sections/interfaces/Hero';
import { Overview_NoRelations } from '../../../../components/sections/interfaces/Overview';
import { Card_NoRelations } from '../../../../components/elements/interfaces/Card';

export interface Home {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    _softDeletedAt?: Date;
    _softDeletedById?: number;
    _softDeletedByType?: string;
    Hero: Hero;
    Overview?: Overview;
    JoinTheTeam: Card[];
  };
}
export interface Home_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  _softDeletedAt?: Date;
  _softDeletedById?: number;
  _softDeletedByType?: string;
  Hero: Hero_Plain;
  Overview?: Overview_Plain;
  JoinTheTeam: Card_Plain[];
}

export interface Home_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  _softDeletedAt?: Date;
  _softDeletedById?: number;
  _softDeletedByType?: string;
  Hero: Hero_NoRelations;
  Overview?: Overview_NoRelations;
  JoinTheTeam: Card_NoRelations[];
}

export interface Home_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  _softDeletedAt?: Date;
  _softDeletedById?: number;
  _softDeletedByType?: string;
  Hero: Hero_Plain;
  Overview?: Overview_Plain;
  JoinTheTeam: Card_Plain[];
}
