// Interface automatically generated by schemas-to-ts

export interface ExpertiseLandingPage {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    Description: string;
  };
}
export interface ExpertiseLandingPage_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  Description: string;
}

export interface ExpertiseLandingPage_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  Description: string;
}

export interface ExpertiseLandingPage_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  Description: string;
}
