// Interface automatically generated by schemas-to-ts

import { Media } from '../../../../common/schemas-to-ts/Media';
import { MetaSocial } from '../../../../components/shared/interfaces/MetaSocial';
import { Expertise } from '../../../expertise/content-types/expertise/expertise';
import { Media_Plain } from '../../../../common/schemas-to-ts/Media';
import { MetaSocial_Plain } from '../../../../components/shared/interfaces/MetaSocial';
import { Expertise_Plain } from '../../../expertise/content-types/expertise/expertise';
import { MetaSocial_NoRelations } from '../../../../components/shared/interfaces/MetaSocial';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Person {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    _softDeletedAt?: Date;
    _softDeletedById?: number;
    _softDeletedByType?: string;
    Avatar: { data: Media };
    Name: string;
    JobTitle: string;
    Location?: string;
    Bio: string;
    Quote?: string;
    Social: MetaSocial[];
    slug: string;
    PhoneNumber?: any;
    expertise: { data: Expertise[] };
  };
}
export interface Person_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  _softDeletedAt?: Date;
  _softDeletedById?: number;
  _softDeletedByType?: string;
  Avatar: Media_Plain;
  Name: string;
  JobTitle: string;
  Location?: string;
  Bio: string;
  Quote?: string;
  Social: MetaSocial_Plain[];
  slug: string;
  PhoneNumber?: any;
  expertise: Expertise_Plain[];
}

export interface Person_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  _softDeletedAt?: Date;
  _softDeletedById?: number;
  _softDeletedByType?: string;
  Avatar: number;
  Name: string;
  JobTitle: string;
  Location?: string;
  Bio: string;
  Quote?: string;
  Social: MetaSocial_NoRelations[];
  slug: string;
  PhoneNumber?: any;
  expertise: number[];
}

export interface Person_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  _softDeletedAt?: Date;
  _softDeletedById?: number;
  _softDeletedByType?: string;
  Avatar: AdminPanelRelationPropertyModification<Media_Plain>;
  Name: string;
  JobTitle: string;
  Location?: string;
  Bio: string;
  Quote?: string;
  Social: MetaSocial_Plain[];
  slug: string;
  PhoneNumber?: any;
  expertise: AdminPanelRelationPropertyModification<Expertise_Plain>;
}
