// Interface automatically generated by schemas-to-ts

import { TitleAndDescription } from '../../../../components/sections/interfaces/TitleAndDescription';
import { PeopleGroupRow } from '../../../../components/sections/interfaces/PeopleGroupRow';
import { TitleAndDescription_Plain } from '../../../../components/sections/interfaces/TitleAndDescription';
import { PeopleGroupRow_Plain } from '../../../../components/sections/interfaces/PeopleGroupRow';
import { TitleAndDescription_NoRelations } from '../../../../components/sections/interfaces/TitleAndDescription';
import { PeopleGroupRow_NoRelations } from '../../../../components/sections/interfaces/PeopleGroupRow';

export interface AboutUsOurPeoplePage {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    _softDeletedAt?: Date;
    _softDeletedById?: number;
    _softDeletedByType?: string;
    Overview?: TitleAndDescription;
    People: PeopleGroupRow[];
  };
}
export interface AboutUsOurPeoplePage_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  _softDeletedAt?: Date;
  _softDeletedById?: number;
  _softDeletedByType?: string;
  Overview?: TitleAndDescription_Plain;
  People: PeopleGroupRow_Plain[];
}

export interface AboutUsOurPeoplePage_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  _softDeletedAt?: Date;
  _softDeletedById?: number;
  _softDeletedByType?: string;
  Overview?: TitleAndDescription_NoRelations;
  People: PeopleGroupRow_NoRelations[];
}

export interface AboutUsOurPeoplePage_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  _softDeletedAt?: Date;
  _softDeletedById?: number;
  _softDeletedByType?: string;
  Overview?: TitleAndDescription_Plain;
  People: PeopleGroupRow_Plain[];
}
