// Interface automatically generated by schemas-to-ts

import { Hero } from '../../../../components/sections/interfaces/Hero';
import { Overview } from '../../../../components/sections/interfaces/Overview';
import { Hero_Plain } from '../../../../components/sections/interfaces/Hero';
import { Overview_Plain } from '../../../../components/sections/interfaces/Overview';
import { Hero_NoRelations } from '../../../../components/sections/interfaces/Hero';
import { Overview_NoRelations } from '../../../../components/sections/interfaces/Overview';

export interface WhyUs {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    Hero?: Hero;
    Overview?: Overview;
  };
}
export interface WhyUs_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  Hero?: Hero_Plain;
  Overview?: Overview_Plain;
}

export interface WhyUs_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  Hero?: Hero_NoRelations;
  Overview?: Overview_NoRelations;
}

export interface WhyUs_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  Hero?: Hero_Plain;
  Overview?: Overview_Plain;
}
