// Interface automatically generated by schemas-to-ts

import { TitleAndDescription } from '../../../../components/sections/interfaces/TitleAndDescription';
import { TitleAndDescription_Plain } from '../../../../components/sections/interfaces/TitleAndDescription';
import { TitleAndDescription_NoRelations } from '../../../../components/sections/interfaces/TitleAndDescription';

export interface CareersOpenRolesPage {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    Overview?: TitleAndDescription;
    Description?: TitleAndDescription;
  };
}
export interface CareersOpenRolesPage_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  Overview?: TitleAndDescription_Plain;
  Description?: TitleAndDescription_Plain;
}

export interface CareersOpenRolesPage_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  Overview?: TitleAndDescription_NoRelations;
  Description?: TitleAndDescription_NoRelations;
}

export interface CareersOpenRolesPage_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  Overview?: TitleAndDescription_Plain;
  Description?: TitleAndDescription_Plain;
}
