// Interface automatically generated by schemas-to-ts

import { TitleAndDescription } from '../../../../components/sections/interfaces/TitleAndDescription';
import { Hero } from '../../../../components/sections/interfaces/Hero';
import { TitleAndDescription_Plain } from '../../../../components/sections/interfaces/TitleAndDescription';
import { Hero_Plain } from '../../../../components/sections/interfaces/Hero';
import { TitleAndDescription_NoRelations } from '../../../../components/sections/interfaces/TitleAndDescription';
import { Hero_NoRelations } from '../../../../components/sections/interfaces/Hero';

export interface CareersOpenRolesPage {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    _softDeletedAt?: Date;
    _softDeletedById?: number;
    _softDeletedByType?: string;
    Overview?: TitleAndDescription;
    Description?: TitleAndDescription;
    Hero?: Hero;
  };
}
export interface CareersOpenRolesPage_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  _softDeletedAt?: Date;
  _softDeletedById?: number;
  _softDeletedByType?: string;
  Overview?: TitleAndDescription_Plain;
  Description?: TitleAndDescription_Plain;
  Hero?: Hero_Plain;
}

export interface CareersOpenRolesPage_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  _softDeletedAt?: Date;
  _softDeletedById?: number;
  _softDeletedByType?: string;
  Overview?: TitleAndDescription_NoRelations;
  Description?: TitleAndDescription_NoRelations;
  Hero?: Hero_NoRelations;
}

export interface CareersOpenRolesPage_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  _softDeletedAt?: Date;
  _softDeletedById?: number;
  _softDeletedByType?: string;
  Overview?: TitleAndDescription_Plain;
  Description?: TitleAndDescription_Plain;
  Hero?: Hero_Plain;
}
